import type { Metadata } from 'next'
import './globals.css'
import { BanksContextProvider } from './hooks/useBanks/index.'
import Link from 'next/link'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <BanksContextProvider>
          <header className="px-5">
            <nav className="navbar bg-base-200 text-base-200-content flex justify-between rounded-full px-5 w-full my-5 mx-auto">
              <Link
                className="text-xl font-semibold capitalize font-sans"
                href="/"
              >
                Finn Sparing
              </Link>
              <div className="flex gap-5">
                <Link href="/banksparinger">Produkter</Link>
                <Link href="/banksparinger" className="indicator">
                  <span className="indicator-item badge badge-accent">5</span>
                  Sammenligne
                </Link>
              </div>
            </nav>
          </header>
          <main className="px-5">{children}</main>
        </BanksContextProvider>
      </body>
    </html>
  )
}
